
package sa.elm.ob.utility.dms.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import sa.elm.ob.utility.dms.org.datacontract.schemas._2004._07.mot_services_dms.ServiceAccount;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDMSLibrary", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    sa.elm.ob.utility.dms.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    sa.elm.ob.utility.dms.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    sa.elm.ob.utility.dms.org.datacontract.schemas._2004._07.mot_services_dms.ObjectFactory.class,
    sa.elm.ob.utility.dms.org.tempuri.ObjectFactory.class
})
public interface IDMSLibrary {


    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "BuildTree", action = "http://tempuri.org/IDMSLibrary/BuildTree")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response buildTree(
        @WebParam(name = "BuildTreeRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        BuildTreeRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "CreateRecordWithAttachment", action = "http://tempuri.org/IDMSLibrary/CreateRecordWithAttachment")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response createRecordWithAttachment(
        @WebParam(name = "CreateRecordWithAttachmentRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        CreateRecordWithAttachmentRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "GetRecord", action = "http://tempuri.org/IDMSLibrary/GetRecord")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response getRecord(
        @WebParam(name = "GetRecordRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        GetRecordRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "CreateRecord", action = "http://tempuri.org/IDMSLibrary/CreateRecord")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response createRecord(
        @WebParam(name = "CreateRecordRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        CreateRecordRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "ModifyRecord", action = "http://tempuri.org/IDMSLibrary/ModifyRecord")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response modifyRecord(
        @WebParam(name = "ModifyRecordRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        ModifyRecordRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "DeleteRecord", action = "http://tempuri.org/IDMSLibrary/DeleteRecord")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response deleteRecord(
        @WebParam(name = "DeleteRecordRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        DeleteRecordRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param ipAddress
     * @param serviceAccount
     * @param parameters
     * @param token
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "GetAttachment", action = "http://tempuri.org/IDMSLibrary/GetAttachment")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response getAttachment(
        @WebParam(name = "GetAttachmentRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        GetAttachmentRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "IPAddress", targetNamespace = "http://tempuri.org/", header = true, partName = "IPAddress")
        String ipAddress,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount,
        @WebParam(name = "Token", targetNamespace = "http://tempuri.org/", header = true, partName = "Token")
        String token);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.AttachmentsBulkResponse
     */
    @WebMethod(operationName = "GetAttachmentsBulk", action = "http://tempuri.org/IDMSLibrary/GetAttachmentsBulk")
    @WebResult(name = "AttachmentsBulkResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public AttachmentsBulkResponse getAttachmentsBulk(
        @WebParam(name = "GetAttachmentsBulkRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        GetAttachmentsBulkRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "AddAttachment", action = "http://tempuri.org/IDMSLibrary/AddAttachment")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response addAttachment(
        @WebParam(name = "AddAttachmentRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        AddAttachmentRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "AddVersionAttachment", action = "http://tempuri.org/IDMSLibrary/AddVersionAttachment")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response addVersionAttachment(
        @WebParam(name = "AddVersionAttachmentRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        AddVersionAttachmentRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

    /**
     * 
     * @param dmsClientID
     * @param serviceAccount
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "DeleteAttachment", action = "http://tempuri.org/IDMSLibrary/DeleteAttachment")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response deleteAttachment(
        @WebParam(name = "DeleteAttachmentRequest", targetNamespace = "http://tempuri.org/", partName = "parameters")
        DeleteAttachmentRequest parameters,
        @WebParam(name = "DmsClientID", targetNamespace = "http://tempuri.org/", header = true, partName = "DmsClientID")
        String dmsClientID,
        @WebParam(name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true, partName = "ServiceAccount")
        ServiceAccount serviceAccount);

}
