(function(s){s.fn.jqm=function(a){var b={overlay:50,closeoverlay:true,overlayClass:"jqmOverlay",closeClass:"jqmClose",trigger:".jqModal",ajax:f,ajaxText:"",target:f,modal:f,toTop:f,onShow:f,onHide:f,onLoad:f};return this.each(function(){if(this._jqm){return m[this._jqm].c=s.extend({},m[this._jqm].c,a);
}e++;this._jqm=e;m[e]={c:s.extend(b,s.jqm.params,a),a:f,w:s(this).addClass("jqmID"+e),s:e};if(b.trigger){s(this).jqmAddTrigger(b.trigger);}});};s.fn.jqmAddClose=function(a){return o(this,a,"jqmHide");};s.fn.jqmAddTrigger=function(a){return o(this,a,"jqmShow");};s.fn.jqmShow=function(a){return this.each(function(){s.jqm.open(this._jqm,a);
});};s.fn.jqmHide=function(a){return this.each(function(){s.jqm.close(this._jqm,a);});};s.jqm={hash:{},open:function(b,d){var c=m[b],a=c.c,g="."+a.closeClass,l=(parseInt(c.w.css("z-index")));l=(l>0)?l:3000;var h=s("<div></div>").css({height:"100%",width:"100%",position:"fixed",left:0,top:0,"z-index":l-1,opacity:a.overlay/100});
if(c.a){return f;}c.t=d;c.a=true;c.w.css("z-index",l);if(a.modal){if(!v[0]){setTimeout(function(){p("bind");},1);}v.push(b);}else{if(a.overlay>0){if(a.closeoverlay){c.w.jqmAddClose(h);}}else{h=f;}}c.o=(h)?h.addClass(a.overlayClass).prependTo("body"):f;if(t){s("html,body").css({height:"100%",width:"100%"});
if(h){h=h.css({position:"absolute"})[0];for(var k in {Top:1,Left:1}){h.style.setExpression(k.toLowerCase(),"(_=(document.documentElement.scroll"+k+" || document.body.scroll"+k+"))+'px'");}}}if(a.ajax){var i=a.target||c.w,j=a.ajax;i=(typeof i=="string")?s(i,c.w):s(i);j=(j.substr(0,1)=="@")?s(d).attr(j.substring(1)):j;
i.html(a.ajaxText).load(j,function(){if(a.onLoad){a.onLoad.call(this,c);}if(g){c.w.jqmAddClose(s(g,c.w));}q(c);});}else{if(g){c.w.jqmAddClose(s(g,c.w));}}if(a.toTop&&c.o){c.w.before('<span id="jqmP'+c.w[0]._jqm+'"></span>').insertAfter(c.o);}(a.onShow)?a.onShow(c):c.w.show();q(c);return f;},close:function(a){var b=m[a];
if(!b.a){return f;}b.a=f;if(v[0]){v.pop();if(!v[0]){p("unbind");}}if(b.c.toTop&&b.o){s("#jqmP"+b.w[0]._jqm).after(b.w).remove();}if(b.c.onHide){b.c.onHide(b);}else{b.w.hide();if(b.o){b.o.remove();}}return f;},params:{}};var e=0,m=s.jqm.hash,v=[],t=s.browser.msie&&(s.browser.version=="6.0"),f=false,q=function(a){var b=s('<iframe src="javascript:false;document.write(\'\');" class="jqm"></iframe>').css({opacity:0});
if(t){if(a.o){a.o.html('<p style="width:100%;height:100%"/>').prepend(b);}else{if(!s("iframe.jqm",a.w)[0]){a.w.prepend(b);}}}r(a);},r=function(a){try{s(":input:visible",a.w)[0].focus();}catch(b){}},p=function(a){s(document)[a]("keypress",u)[a]("keydown",u)[a]("mousedown",u);},u=function(c){var b=m[v[v.length-1]],a=(!s(c.target).parents(".jqmID"+b.s)[0]);
if(a){r(b);}return !a;},o=function(c,b,a){return c.each(function(){var d=this._jqm;s(b).each(function(){if(!this[a]){this[a]=[];s(this).click(function(){for(var h in {jqmShow:1,jqmHide:1}){for(var g in this[h]){if(m[this[h][g]]){m[this[h][g]].w[h](this);}}}return f;});}this[a].push(d);});});};})(jQuery);
