var TCR=new Tcalculator();function Tcalculator(){this.oper_old=this.oper_old_old=this.slag_1=this.slag_2=this.slag_1_old=this.out_val=this.p_out="";this.t_load=false;this.TCRisNumber=TCRisNumber;this.TCRisPoint=TCRisPoint;this.TCRPopup=TCRPopup;this.TCRrezult=TCRrezult;this.TCRmntr=TCRmntr;var a=[],c,b;
var d;if(typeof baseDirectory!="unknown"){d=(baseDirectory==null||baseDirectory=="");}else{d=(baseDirection==null||baseDirection=="");}if(d){for(c=0;c<19;c++){a[c]=[];for(b=0;b<3;b++){a[c][b]=new Image();a[c][b].src="images/calculator/"+c+"_"+b+".gif";}}}}function TCRisPoint(tmp,n){var flag=0;if(tmp=="."){var tmp2=window.win_ch.document.forms[0].elements[0].value;
for(var i=0;i<tmp2.length;i++){thischar=tmp2.substring(i,i+1);if(thischar=="."){flag=1;}}}if(flag==0){eval("this.slag_"+n+"+=tmp;");}}function TCRisNumber(e){var f="0123456789",d,b=p_counter=err_cod=popr=0,a=e.length,c;for(c=0;c<a;c++){d=e.substring(c,c+1);if(f.indexOf(d)!=-1){b++;}if(d=="-"){if(c!=0){err_cod=1;
break;}else{popr++;}}if(d=="."){if((c==0||c==a-1)||(c==1&&e.substring(c-1,c)=="-")){err_cod=1;break;}else{p_counter++;if(p_counter>1){err_cod=1;break;}else{popr++;}}}}if(err_cod!=1&&b==a-popr){return true;}else{return false;}}function TCRrezult(slag_1,slag_2,oper){slag_1=parseFloat(slag_1);slag_2=parseFloat(slag_2);
eval("out=("+slag_1+")"+oper+"("+slag_2+")");return out;}function TCRPopup(g){var c=getGlobalDecSeparator();var e=getGlobalGroupSeparator();var a=186,f=122;var d=navigator.userAgent.toLowerCase();var b=navigator.appVersion.substring(0,1);var i=navigator.appName.toLowerCase();if(!g){return alert("Form element specified can't be found in the document.");
}this.control_obj=g;this.control_obj_value_calc_format=returnFormattedToCalc(this.control_obj.value,c,e);if(!this.TCRisNumber(this.control_obj_value_calc_format)){alert("wrong data");}else{if(d.indexOf("opera")>0){a=176;f=135;}else{if(d.indexOf("netscape")<0&&d.indexOf("msie")<0&&b>=5&&d.indexOf("mac")>0){a=212;
f=122;}else{if(i=="netscape"){if(b==4){a=216;f=128;}if(b>=5){a=185;f=126;}}}}a+=36;f+=66;if(screen){n_left=(screen.width-a)>>1;n_top=(screen.height-f)>>1;}if(typeof baseDirectory!="unknown"){win_ch=window.open(baseDirectory+"popups/calculator.html","win_ch","width="+a+",height="+f+",help=no,status=no,scrollbars=no,resizable=no,top="+n_top+",left="+n_left+",dependent=yes,alwaysRaised=yes",true);
}else{win_ch=window.open(baseDirection+"popups/calculator.html","win_ch","width="+a+",height="+f+",help=no,status=no,scrollbars=no,resizable=no,top="+n_top+",left="+n_left+",dependent=yes,alwaysRaised=yes",true);}win_ch.focus();}}function TCRmntr(c){var b=getGlobalDecSeparator();var a=0;if(this.t_load){tmp=window.win_ch.document.forms[0].elements[0].value;
}if(c=="C"){this.out_val="0";this.oper_old=this.oper_old_old=this.slag_1=this.slag_2="";}else{if(tmp!="NaN"&&tmp!="Infinity"){switch(c){case"-":case"+":case"/":case"*":if(this.slag_1!=""&&this.slag_2!=""){this.out_val=this.slag_1=this.TCRrezult(this.slag_1,this.slag_2,this.oper_old);this.slag_2="";}else{if(this.slag_1==""&&this.slag_2==""){this.out_val=this.slag_1=tmp;
}}this.oper_old=c;break;case"sqr":this.slag_1=tmp;this.slag_2="";this.slag_1=parseFloat(this.slag_1);this.slag_1=Math.sqrt(this.slag_1);this.oper_old=this.oper_old_old="";this.out_val=this.slag_1;this.out_val=this.out_val.toString();this.control_obj.value=this.out_val.replace(".",b);if(focusedWindowElement!=this.control_obj){if(typeof this.control_obj.onblur=="function"){this.control_obj.onblur();
}}if(typeof this.control_obj.onchange=="function"){this.control_obj.onchange();}break;case"=":if(this.oper_old!=""){if(this.slag_1!=""&&this.slag_2!=""){this.out_val=this.TCRrezult(this.slag_1,this.slag_2,this.oper_old);this.slag_1=this.slag_1_old=this.slag_2;}else{if(this.slag_1!=""&&this.slag_2==""){this.out_val=this.TCRrezult(this.slag_1,this.slag_1,this.oper_old);
this.slag_1_old=this.slag_1;}}this.oper_old_old=this.oper_old;this.slag_2="";this.slag_1="";this.oper_old="";}else{if(this.oper_old_old!=""){this.slag_2_old=tmp;this.out_val=this.TCRrezult(this.slag_2_old,this.slag_1_old,this.oper_old_old);}else{if(this.slag_1==""&&this.slag_2==""){this.out_val="0";}else{this.out_val=this.slag_1;
}}}this.out_val=this.out_val.toString();this.control_obj.value=this.out_val.replace(".",b);if(focusedWindowElement!=this.control_obj){if(typeof this.control_obj.onblur=="function"){this.control_obj.onblur();}}if(typeof this.control_obj.onchange=="function"){this.control_obj.onchange();}break;case"z":tmp=parseFloat(tmp);
this.out_val=tmp*-1;if(this.slag_1!=""&&this.slag_2==""){this.slag_1=this.out_val;}else{if(this.slag_2!=""){this.slag_2=this.out_val;}}break;default:if(this.oper_old==""){if(c=="0"&&tmp=="0"){this.slag_1=tmp;}else{if(c=="."&&tmp=="0"){this.slag_1=tmp+c;}else{if(c=="."&&this.slag_1==""){this.slag_1="0"+c;
}else{if(c=="."||this.slag_1!=""){this.TCRisPoint(c,"1");}else{this.slag_1=c;}}}}this.out_val=this.slag_1;}else{if(c=="0"&&tmp=="0"){this.slag_2=tmp;}else{if(c=="."&&this.slag_2==""){this.slag_2="0"+c;}else{if(c=="."||this.slag_2!=""){this.TCRisPoint(c,"2");}else{this.slag_2=c;}}}this.out_val=this.slag_2;
}}}}if(this.t_load){window.win_ch.document.forms[0].elements[0].value=this.out_val;}}function calculator(item,value,debug){return TCR.TCRPopup(eval(item));}