var gDefaultType=0;if(typeof arrMessages==="undefined"){var arrMessages;var arrTypes;if(typeof getFrame==="function"&&getFrame("frameMenu")){arrMessages=getFrame("frameMenu").arrMessages;arrTypes=getFrame("frameMenu").arrTypes;}else{if(parent&&parent.frameMenu){arrMessages=parent.frameMenu.arrMessages;
arrTypes=parent.frameMenu.arrTypes;}else{if(top&&top.opener&&top.opener.parent&&top.opener.parent.frameMenu){arrMessages=top.opener.parent.frameMenu.arrMessages;arrTypes=top.opener.parent.frameMenu.arrTypes;}else{if(top&&top.opener&&top.opener.top&&top.opener.top.opener&&top.opener.top.opener.parent&&top.opener.top.opener.parent.frameMenu){arrMessages=top.opener.top.opener.parent.frameMenu.arrMessages;
arrTypes=top.opener.top.opener.parent.frameMenu.arrTypes;}}}}}function messageType(b,a){this.id=b;this.type=a;}function messagesTexts(a,b,c,d){this.language=a;this.message=b;this.text=c;this.defaultText=d;}function getMessage(b,a){if(a==null){if(typeof defaultLang!="undefined"){a=defaultLang;}else{if(typeof LNG_POR_DEFECTO!="undefined"){a=LNG_POR_DEFECTO;
}}}var d=(arrMessages?arrMessages.length:0);for(var c=0;c<d;c++){if(arrMessages[c].language==a){if(arrMessages[c].message==b){return(arrMessages[c].text);}}}return null;}function getDefaultText(b,a){if(a==null){if(typeof defaultLang!="undefined"){a=defaultLang;}else{if(typeof LNG_POR_DEFECTO!="undefined"){a=LNG_POR_DEFECTO;
}}}var d=(arrMessages?arrMessages.length:0);for(var c=0;c<d;c++){if(arrMessages[c].language==a){if(arrMessages[c].message==b){return(arrMessages[c].defaultText);}}}return null;}function getType(a){var c=arrTypes.length;for(var b=0;b<c;b++){if(arrTypes[b].id==a){return(arrTypes[b].type);}}return null;
}function showStdMessage(c,b,a){switch(b){case 1:return confirm(c);break;case 2:return prompt(c,a);break;default:alert(c);}return true;}function showMessage(c,b,a){return showStdMessage(c,b,a);}function mensaje(b,a){showJSMessage(b,a);}function showJSMessage(f,d,g,b){var j=typeof g=="undefined"||g==null?true:g;
if(j){try{initialize_MessageBox("messageBoxID");}catch(a){}}var e=getMessage(f,d);if(e==null){e=getMessage(f,"en_US");}if(e==null){getDataBaseMessage(f,null,b);return true;}var c=getDefaultText(f,d);if(c==null){c=getDefaultText(f,"en_US");}var h=getType(f,d);if(h==null){h=gDefaultType;}return showStdMessage(e,h,c);
}function renderMessageBox(a,d,c){try{dojo.widget.byId("messageBoxID").setValues(a,d,c);}catch(b){alert(d+":\n"+c);}return true;}function getUrl(){var a=window.location.href;var c=a.indexOf("://");var b=a.indexOf("/",c+3);if(b!=-1){b=a.indexOf("/",b+1);if(b!=-1){a=a.substring(0,b);}}return a;}function getDataBaseMessage(d,c,f){var e=getAppUrl();
var b=null;var a;if(new RegExp("^[0-9]+$").test(d)){a="JS"+d;}else{a=d;}if(f){submitXmlHttpRequestUrl(((c==null)?messageResponse:c),(e+"/businessUtility/MessageJS.html?inpvalue="+escape(a)+"&inpparams="+escape(isc.JSONEncoder.echo(f))),false,b);}else{submitXmlHttpRequestUrl(((c==null)?messageResponse:c),(e+"/businessUtility/MessageJS.html?inpvalue="+escape(a)),false,b);
}}function getDataBaseStandardMessage(c,b){var d=getAppUrl();var a=null;submitXmlHttpRequestUrl(((b==null)?messageResponse:b),(d+"/businessUtility/MessageJS.html?inpvalue="+escape(c)),false,a);}function messageResponse(a,c){var f;if(getReadyStateHandler(c)){try{if(c.responseXML){f=c.responseXML.documentElement;
}}catch(g){}if(f){var d=f.getElementsByTagName("status");if(d.length>0){var h=d[0].getElementsByTagName("type");var j=d[0].getElementsByTagName("title");var k=d[0].getElementsByTagName("description");try{setValues_MessageBox("messageBoxID",h[0].firstChild.nodeValue.toUpperCase(),j[0].firstChild.nodeValue,k[0].firstChild.nodeValue);
}catch(b){alert(j[0].firstChild.nodeValue+":\n"+k[0].firstChild.nodeValue);}}}}return true;}function setValidationMessages(){var a=getMessage("Missing");var d=getElementsByName("missingText","div");for(i=0;i<d.length;i++){d[i].innerHTML=a;}var c=getMessage("Invalid");var b=getElementsByName("invalidText","div");
for(i=0;i<b.length;i++){b[i].innerHTML=c;}}