package sa.elm.ob.utility.sadad.consumer.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import org.tempuri.GetSaddadUnPaidBillsRequest;

/**
 * This class was generated by Apache CXF 3.2.7 2019-01-06T15:52:33.001+03:00 Generated source
 * version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ISaddadLibrary")
@XmlSeeAlso({
    sa.elm.ob.utility.sadad.consumer.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    ObjectFactory.class,
    sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ISaddadLibrary {

  @WebMethod(operationName = "GetMOT_SubAccountsByApplicationType", action = "http://tempuri.org/ISaddadLibrary/GetMOT_SubAccountsByApplicationType")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetMOT_SubAccountsByApplicationType", output = "http://tempuri.org/ISaddadLibrary/GetMOT_SubAccountsByApplicationTypeResponse")
  @WebResult(name = "MOT_SubAccountsResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public MOTSubAccountsResponse getMOTSubAccountsByApplicationType(
      @WebParam(partName = "parameters", name = "GetMOT_SubAccountsByApplicationTypeRequest", targetNamespace = "http://tempuri.org/") GetMOTSubAccountsByApplicationTypeRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "DeleteSaddadBill", action = "http://tempuri.org/ISaddadLibrary/DeleteSaddadBill")
  @Action(input = "http://tempuri.org/ISaddadLibrary/DeleteSaddadBill", output = "http://tempuri.org/ISaddadLibrary/DeleteSaddadBillResponse")
  @WebResult(name = "DeleteSaddadBillResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public DeleteSaddadBillResponse deleteSaddadBill(
      @WebParam(partName = "parameters", name = "DeleteSaddadBillRequest", targetNamespace = "http://tempuri.org/") DeleteSaddadBillRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetSaddadBill", action = "http://tempuri.org/ISaddadLibrary/GetSaddadBill")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetSaddadBill", output = "http://tempuri.org/ISaddadLibrary/GetSaddadBillResponse")
  @WebResult(name = "GetSaddadBillResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public GetSaddadBillResponse getSaddadBill(
      @WebParam(partName = "parameters", name = "GetSaddadBillRequest", targetNamespace = "http://tempuri.org/") GetSaddadBillRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetMOT_SubAccountsByID", action = "http://tempuri.org/ISaddadLibrary/GetMOT_SubAccountsByID")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetMOT_SubAccountsByID", output = "http://tempuri.org/ISaddadLibrary/GetMOT_SubAccountsByIDResponse")
  @WebResult(name = "MOT_SubAccountsResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public MOTSubAccountsResponse getMOTSubAccountsByID(
      @WebParam(partName = "parameters", name = "GetMOT_SubAccountsByIdRequest", targetNamespace = "http://tempuri.org/") GetMOTSubAccountsByIdRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetAllMOT_SubAccounts", action = "http://tempuri.org/ISaddadLibrary/GetAllMOT_SubAccounts")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetAllMOT_SubAccounts", output = "http://tempuri.org/ISaddadLibrary/GetAllMOT_SubAccountsResponse")
  @WebResult(name = "MOT_SubAccountsResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public MOTSubAccountsResponse getAllMOTSubAccounts(
      @WebParam(partName = "parameters", name = "GetAllMOT_SubAccountsRequest", targetNamespace = "http://tempuri.org/") GetAllMOTSubAccountsRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetSaddadUnPaidBillsCount", action = "http://tempuri.org/ISaddadLibrary/GetSaddadUnPaidBillsCount")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetSaddadUnPaidBillsCount", output = "http://tempuri.org/ISaddadLibrary/GetSaddadUnPaidBillsCountResponse")
  @WebResult(name = "GetSaddadUnPaidBillsCountResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public GetSaddadUnPaidBillsCountResponse getSaddadUnPaidBillsCount(
      @WebParam(partName = "parameters", name = "GetSaddadUnPaidBillsCountRequest", targetNamespace = "http://tempuri.org/") GetSaddadUnPaidBillsCountRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetAllMainAccounts", action = "http://tempuri.org/ISaddadLibrary/GetAllMainAccounts")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetAllMainAccounts", output = "http://tempuri.org/ISaddadLibrary/GetAllMainAccountsResponse")
  @WebResult(name = "MainAccountsResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public MainAccountsResponse getAllMainAccounts(
      @WebParam(partName = "parameters", name = "GetAllMainAccountsRequest", targetNamespace = "http://tempuri.org/") GetAllMainAccountsRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetMainAccountByID", action = "http://tempuri.org/ISaddadLibrary/GetMainAccountByID")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetMainAccountByID", output = "http://tempuri.org/ISaddadLibrary/GetMainAccountByIDResponse")
  @WebResult(name = "MainAccountsResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public MainAccountsResponse getMainAccountByID(
      @WebParam(partName = "parameters", name = "GetMainAccountByIdRequest", targetNamespace = "http://tempuri.org/") GetMainAccountByIdRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetAllApplicationTypes", action = "http://tempuri.org/ISaddadLibrary/GetAllApplicationTypes")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetAllApplicationTypes", output = "http://tempuri.org/ISaddadLibrary/GetAllApplicationTypesResponse")
  @WebResult(name = "ApplicationTypesResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public ApplicationTypesResponse getAllApplicationTypes(
      @WebParam(partName = "parameters", name = "GetAllApplicationTypesRequest", targetNamespace = "http://tempuri.org/") GetAllApplicationTypesRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetAllIdTypes", action = "http://tempuri.org/ISaddadLibrary/GetAllIdTypes")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetAllIdTypes", output = "http://tempuri.org/ISaddadLibrary/GetAllIdTypesResponse")
  @WebResult(name = "IdTypesResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public IdTypesResponse getAllIdTypes(
      @WebParam(partName = "parameters", name = "GetAllIdTypesRequest", targetNamespace = "http://tempuri.org/") GetAllIdTypesRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetAllCustomerTypes", action = "http://tempuri.org/ISaddadLibrary/GetAllCustomerTypes")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetAllCustomerTypes", output = "http://tempuri.org/ISaddadLibrary/GetAllCustomerTypesResponse")
  @WebResult(name = "CustomerTypesResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public CustomerTypesResponse getAllCustomerTypes(
      @WebParam(partName = "parameters", name = "GetAllCustomerTypesRequest", targetNamespace = "http://tempuri.org/") GetAllCustomerTypesRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "AddNewSaddadBill", action = "http://tempuri.org/ISaddadLibrary/AddNewSaddadBill")
  @Action(input = "http://tempuri.org/ISaddadLibrary/AddNewSaddadBill", output = "http://tempuri.org/ISaddadLibrary/AddNewSaddadBillResponse")
  @WebResult(name = "AddSaddadBillResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public AddSaddadBillResponse addNewSaddadBill(
      @WebParam(partName = "parameters", name = "AddSaddadBillRequest", targetNamespace = "http://tempuri.org/") AddSaddadBillRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);

  @WebMethod(operationName = "GetSaddadUnPaidBills", action = "http://tempuri.org/ISaddadLibrary/GetSaddadUnPaidBills")
  @Action(input = "http://tempuri.org/ISaddadLibrary/GetSaddadUnPaidBills", output = "http://tempuri.org/ISaddadLibrary/GetSaddadUnPaidBillsResponse")
  @WebResult(name = "GetSaddadUnPaidBillsResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
  public GetSaddadUnPaidBillsResponse getSaddadUnPaidBills(
      @WebParam(partName = "parameters", name = "GetSaddadUnPaidBillsRequest", targetNamespace = "http://tempuri.org/") GetSaddadUnPaidBillsRequest parameters,
      @WebParam(partName = "ServiceAccount", name = "ServiceAccount", targetNamespace = "http://tempuri.org/", header = true) sa.elm.ob.utility.sadad.consumer.org.datacontract.schemas._2004._07.mot_services_saddad.ServiceAccount serviceAccount);
}
