//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.20 at 12:05:07 PM AST 
//


package sa.elm.ob.utility.sadad.producer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sa.elm.grp.bill package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceAccount_QNAME = new QName("http://elm.sa/grp/soap", "serviceAccount");
    private final static QName _SadadBillResponseErrorMessage_QNAME = new QName("http://elm.sa/grp/soap", "ErrorMessage");
    private final static QName _ServiceAccountUserName_QNAME = new QName("http://elm.sa/grp/soap", "UserName");
    private final static QName _ServiceAccountPassword_QNAME = new QName("http://elm.sa/grp/soap", "Password");
    private final static QName _ServiceAccountServiceKey_QNAME = new QName("http://elm.sa/grp/soap", "ServiceKey");
    private final static QName _SadadBillRequestMobileNo_QNAME = new QName("http://elm.sa/grp/soap", "MobileNo");
    private final static QName _SadadBillRequestIDNo_QNAME = new QName("http://elm.sa/grp/soap", "IDNo");
    private final static QName _SadadBillRequestNotes_QNAME = new QName("http://elm.sa/grp/soap", "Notes");
    private final static QName _SadadBillRequestCustomerName_QNAME = new QName("http://elm.sa/grp/soap", "CustomerName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sa.elm.grp.bill
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SadadBillResponse }
     * 
     */
    public SadadBillResponse createSadadBillResponse() {
        return new SadadBillResponse();
    }

    /**
     * Create an instance of {@link ServiceAccount }
     * 
     */
    public ServiceAccount createServiceAccount() {
        return new ServiceAccount();
    }

    /**
     * Create an instance of {@link SadadBillRequest }
     * 
     */
    public SadadBillRequest createSadadBillRequest() {
        return new SadadBillRequest();
    }

    /**
     * Create an instance of {@link SadadBillDetail }
     * 
     */
    public SadadBillDetail createSadadBillDetail() {
        return new SadadBillDetail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "serviceAccount")
    public JAXBElement<ServiceAccount> createServiceAccount(ServiceAccount value) {
        return new JAXBElement<ServiceAccount>(_ServiceAccount_QNAME, ServiceAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "ErrorMessage", scope = SadadBillResponse.class)
    public JAXBElement<String> createSadadBillResponseErrorMessage(String value) {
        return new JAXBElement<String>(_SadadBillResponseErrorMessage_QNAME, String.class, SadadBillResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "UserName", scope = ServiceAccount.class)
    public JAXBElement<String> createServiceAccountUserName(String value) {
        return new JAXBElement<String>(_ServiceAccountUserName_QNAME, String.class, ServiceAccount.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "Password", scope = ServiceAccount.class)
    public JAXBElement<String> createServiceAccountPassword(String value) {
        return new JAXBElement<String>(_ServiceAccountPassword_QNAME, String.class, ServiceAccount.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "ServiceKey", scope = ServiceAccount.class)
    public JAXBElement<String> createServiceAccountServiceKey(String value) {
        return new JAXBElement<String>(_ServiceAccountServiceKey_QNAME, String.class, ServiceAccount.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "MobileNo", scope = SadadBillRequest.class)
    public JAXBElement<String> createSadadBillRequestMobileNo(String value) {
        return new JAXBElement<String>(_SadadBillRequestMobileNo_QNAME, String.class, SadadBillRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "IDNo", scope = SadadBillRequest.class)
    public JAXBElement<String> createSadadBillRequestIDNo(String value) {
        return new JAXBElement<String>(_SadadBillRequestIDNo_QNAME, String.class, SadadBillRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "Notes", scope = SadadBillRequest.class)
    public JAXBElement<String> createSadadBillRequestNotes(String value) {
        return new JAXBElement<String>(_SadadBillRequestNotes_QNAME, String.class, SadadBillRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://elm.sa/grp/soap", name = "CustomerName", scope = SadadBillRequest.class)
    public JAXBElement<String> createSadadBillRequestCustomerName(String value) {
        return new JAXBElement<String>(_SadadBillRequestCustomerName_QNAME, String.class, SadadBillRequest.class, value);
    }

}
