//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.20 at 12:05:07 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://elm.sa/grp/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sa.elm.ob.utility.sadad.producer;
