
package sa.elm.ob.utility.dms.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import sa.elm.ob.utility.dms.util.GetServiceAccount;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version:
 * 2.2
 * 
 */
@WebServiceClient(name = "DMSLibrary", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://stg-echannel.mot.gov.sa/DMS/DMSService.svc?wsdl")
public class DMSLibrary extends Service {

  private final static URL DMSLIBRARY_WSDL_LOCATION;
  private final static WebServiceException DMSLIBRARY_EXCEPTION;
  private final static QName DMSLIBRARY_QNAME = new QName("http://tempuri.org/", "DMSLibrary");
  private final static String DMS_WSDL_URL = "DMS.wsdl.url";

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL(GetServiceAccount.getProperty(DMS_WSDL_URL));
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    DMSLIBRARY_WSDL_LOCATION = url;
    DMSLIBRARY_EXCEPTION = e;
  }

  public DMSLibrary() {
    super(__getWsdlLocation(), DMSLIBRARY_QNAME);
  }

  public DMSLibrary(WebServiceFeature... features) {
    super(__getWsdlLocation(), DMSLIBRARY_QNAME, features);
  }

  public DMSLibrary(URL wsdlLocation) {
    super(wsdlLocation, DMSLIBRARY_QNAME);
  }

  public DMSLibrary(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, DMSLIBRARY_QNAME, features);
  }

  public DMSLibrary(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public DMSLibrary(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * 
   * @return returns IDMSLibrary
   */
  @WebEndpoint(name = "BasicHttpBinding_IDMSLibrary")
  public IDMSLibrary getBasicHttpBindingIDMSLibrary() {
    return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDMSLibrary"),
        IDMSLibrary.class);
  }

  /**
   * 
   * @param features
   *          A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
   *          features not in the <code>features</code> parameter will have their default values.
   * @return returns IDMSLibrary
   */
  @WebEndpoint(name = "BasicHttpBinding_IDMSLibrary")
  public IDMSLibrary getBasicHttpBindingIDMSLibrary(WebServiceFeature... features) {
    return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDMSLibrary"),
        IDMSLibrary.class, features);
  }

  private static URL __getWsdlLocation() {
    if (DMSLIBRARY_EXCEPTION != null) {
      throw DMSLIBRARY_EXCEPTION;
    }
    return DMSLIBRARY_WSDL_LOCATION;
  }

}
