
package sa.elm.ob.utility.gsb.adf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Interface1", targetNamespace = "http://schemas.nevatech.com/services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Interface1 {


    /**
     * 
     * @param nationalId
     * @return
     *     returns sa.elm.ob.utility.gsb.adf.GetLoanInformationResponseStructure
     * @throws Interface1GetLoanInformationCommonErrorElementFaultMessage
     */
    @WebMethod(operationName = "GetLoanInformation", action = "http://tempuri.org/IClientFinancialStatusService/GetLoanInformation")
    @WebResult(name = "GetLoanInformationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLoanInformation", targetNamespace = "http://tempuri.org/", className = "sa.elm.ob.utility.gsb.adf.GetLoanInformation")
    @ResponseWrapper(localName = "GetLoanInformationResponse", targetNamespace = "http://tempuri.org/", className = "sa.elm.ob.utility.gsb.adf.GetLoanInformationResponse")
    public GetLoanInformationResponseStructure getLoanInformation(
        @WebParam(name = "NationalId", targetNamespace = "http://tempuri.org/")
        String nationalId)
        throws Interface1GetLoanInformationCommonErrorElementFaultMessage
    ;

}
