
package sa.elm.ob.utility.gsb.redf;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import sa.elm.ob.utility.util.Utility;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version:
 * 2.2
 * 
 */
@WebServiceClient(name = "GSB-REDF-LI-V-V2", targetNamespace = "http://schemas.nevatech.com/services/", wsdlLocation = "https://stg-api.mot.gov.sa/GSN/REDF/LI/V2?singleWsdl")
public class GSBREDFLIVV2 extends Service {

  private final static URL GSBREDFLIVV2_WSDL_LOCATION;
  private final static WebServiceException GSBREDFLIVV2_EXCEPTION;
  private final static QName GSBREDFLIVV2_QNAME = new QName("http://schemas.nevatech.com/services/",
      "GSB-REDF-LI-V-V2");
  private final static String GSB_REDF_URL = "GSB.redf.wsdl.url";

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL(Utility.getProperty(GSB_REDF_URL));
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    GSBREDFLIVV2_WSDL_LOCATION = url;
    GSBREDFLIVV2_EXCEPTION = e;
  }

  public GSBREDFLIVV2() {
    super(__getWsdlLocation(), GSBREDFLIVV2_QNAME);
  }

  public GSBREDFLIVV2(WebServiceFeature... features) {
    super(__getWsdlLocation(), GSBREDFLIVV2_QNAME, features);
  }

  public GSBREDFLIVV2(URL wsdlLocation) {
    super(wsdlLocation, GSBREDFLIVV2_QNAME);
  }

  public GSBREDFLIVV2(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, GSBREDFLIVV2_QNAME, features);
  }

  public GSBREDFLIVV2(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public GSBREDFLIVV2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * 
   * @return returns Interface1
   */
  @WebEndpoint(name = "GSB-REDF-LI-V-V1-EP")
  public Interface1 getGSBREDFLIVV1EP() {
    return super.getPort(new QName("http://schemas.nevatech.com/services/", "GSB-REDF-LI-V-V1-EP"),
        Interface1.class);
  }

  /**
   * 
   * @param features
   *          A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
   *          features not in the <code>features</code> parameter will have their default values.
   * @return returns Interface1
   */
  @WebEndpoint(name = "GSB-REDF-LI-V-V1-EP")
  public Interface1 getGSBREDFLIVV1EP(WebServiceFeature... features) {
    return super.getPort(new QName("http://schemas.nevatech.com/services/", "GSB-REDF-LI-V-V1-EP"),
        Interface1.class, features);
  }

  private static URL __getWsdlLocation() {
    if (GSBREDFLIVV2_EXCEPTION != null) {
      throw GSBREDFLIVV2_EXCEPTION;
    }
    return GSBREDFLIVV2_WSDL_LOCATION;
  }

}
