
package sa.elm.ob.utility.gsb.adf;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import sa.elm.ob.utility.util.Utility;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version:
 * 2.2
 * 
 */
@WebServiceClient(name = "GSB-ADF-CLFS-V-V1", targetNamespace = "http://schemas.nevatech.com/services/", wsdlLocation = "https://stg-api.mot.gov.sa/GSN/ADF/CLFS/V1?singleWsdl")
public class GSBADFCLFSVV1 extends Service {

  private final static URL GSBADFCLFSVV1_WSDL_LOCATION;
  private final static WebServiceException GSBADFCLFSVV1_EXCEPTION;
  private final static QName GSBADFCLFSVV1_QNAME = new QName(
      "http://schemas.nevatech.com/services/", "GSB-ADF-CLFS-V-V1");
  private final static String GSB_ADF_URL = "GSB.adf.wsdl.url";

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL(Utility.getProperty(GSB_ADF_URL));
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    GSBADFCLFSVV1_WSDL_LOCATION = url;
    GSBADFCLFSVV1_EXCEPTION = e;
  }

  public GSBADFCLFSVV1() {
    super(__getWsdlLocation(), GSBADFCLFSVV1_QNAME);
  }

  public GSBADFCLFSVV1(WebServiceFeature... features) {
    super(__getWsdlLocation(), GSBADFCLFSVV1_QNAME, features);
  }

  public GSBADFCLFSVV1(URL wsdlLocation) {
    super(wsdlLocation, GSBADFCLFSVV1_QNAME);
  }

  public GSBADFCLFSVV1(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, GSBADFCLFSVV1_QNAME, features);
  }

  public GSBADFCLFSVV1(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public GSBADFCLFSVV1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * 
   * @return returns Interface1
   */
  @WebEndpoint(name = "GSB-ADF-CLFS-V-V1-EP")
  public Interface1 getGSBADFCLFSVV1EP() {
    return super.getPort(new QName("http://schemas.nevatech.com/services/", "GSB-ADF-CLFS-V-V1-EP"),
        Interface1.class);
  }

  /**
   * 
   * @param features
   *          A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
   *          features not in the <code>features</code> parameter will have their default values.
   * @return returns Interface1
   */
  @WebEndpoint(name = "GSB-ADF-CLFS-V-V1-EP")
  public Interface1 getGSBADFCLFSVV1EP(WebServiceFeature... features) {
    return super.getPort(new QName("http://schemas.nevatech.com/services/", "GSB-ADF-CLFS-V-V1-EP"),
        Interface1.class, features);
  }

  private static URL __getWsdlLocation() {
    if (GSBADFCLFSVV1_EXCEPTION != null) {
      throw GSBADFCLFSVV1_EXCEPTION;
    }
    return GSBADFCLFSVV1_WSDL_LOCATION;
  }

}
