
package sa.elm.ob.utility.gsb.sdb;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import sa.elm.ob.utility.util.Utility;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035 Generated source version:
 * 2.2
 * 
 */
@WebServiceClient(name = "GSB-SDB-LI-V-V1", targetNamespace = "http://schemas.nevatech.com/services/", wsdlLocation = "https://stg-api.mot.gov.sa/GSN/SDB/LI/V1?singleWsdl")
public class GSBSDBLIVV1 extends Service {

  private final static URL GSBSDBLIVV1_WSDL_LOCATION;
  private final static WebServiceException GSBSDBLIVV1_EXCEPTION;
  private final static QName GSBSDBLIVV1_QNAME = new QName("http://schemas.nevatech.com/services/",
      "GSB-SDB-LI-V-V1");
  private final static String GSB_SDB_URL = "GSB.sdb.wsdl.url";

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL(Utility.getProperty(GSB_SDB_URL));
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    GSBSDBLIVV1_WSDL_LOCATION = url;
    GSBSDBLIVV1_EXCEPTION = e;
  }

  public GSBSDBLIVV1() {
    super(__getWsdlLocation(), GSBSDBLIVV1_QNAME);
  }

  public GSBSDBLIVV1(WebServiceFeature... features) {
    super(__getWsdlLocation(), GSBSDBLIVV1_QNAME, features);
  }

  public GSBSDBLIVV1(URL wsdlLocation) {
    super(wsdlLocation, GSBSDBLIVV1_QNAME);
  }

  public GSBSDBLIVV1(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, GSBSDBLIVV1_QNAME, features);
  }

  public GSBSDBLIVV1(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public GSBSDBLIVV1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * 
   * @return returns Interface1
   */
  @WebEndpoint(name = "GSB-SDB-LI-V-V1-EP")
  public Interface1 getGSBSDBLIVV1EP() {
    return super.getPort(new QName("http://schemas.nevatech.com/services/", "GSB-SDB-LI-V-V1-EP"),
        Interface1.class);
  }

  /**
   * 
   * @param features
   *          A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
   *          features not in the <code>features</code> parameter will have their default values.
   * @return returns Interface1
   */
  @WebEndpoint(name = "GSB-SDB-LI-V-V1-EP")
  public Interface1 getGSBSDBLIVV1EP(WebServiceFeature... features) {
    return super.getPort(new QName("http://schemas.nevatech.com/services/", "GSB-SDB-LI-V-V1-EP"),
        Interface1.class, features);
  }

  private static URL __getWsdlLocation() {
    if (GSBSDBLIVV1_EXCEPTION != null) {
      throw GSBSDBLIVV1_EXCEPTION;
    }
    return GSBSDBLIVV1_WSDL_LOCATION;
  }

}
