
package sa.elm.ob.utility.gsb.redf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "commonErrorElement", targetNamespace = "http://tempuri.org/")
public class Interface1GetLoanDetailsCommonErrorElementFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CommonErrorStructure faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Interface1GetLoanDetailsCommonErrorElementFaultMessage(String message, CommonErrorStructure faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Interface1GetLoanDetailsCommonErrorElementFaultMessage(String message, CommonErrorStructure faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sa.elm.ob.utility.gsb.redf.CommonErrorStructure
     */
    public CommonErrorStructure getFaultInfo() {
        return faultInfo;
    }

}
